#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := OTakuCal

EXTRA_COMPONENT_DIRS := ./Source

COMPONENT_ADD_INCLUDEDIRS := ./Source/Header

include $(IDF_PATH)/make/project.mk

